/* Generated automatically by tools/update-events.ps1. */
window.SPOTI_EVENTS = [
  {
    "id": "unicum-2026-2026-07-08",
    "title": "UNICUM 2026",
    "category": "Glasba",
    "date": "2026-07-08",
    "endDate": "2026-10-15",
    "startTime": "10:00",
    "endTime": "18:00",
    "place": "National Museum of Slovenia (Muzejska ulica 1), NMS Metelkova (Maistrova ulica 1) and Center Rog (Trubarjeva cesta 72), 1000 Ljubljana",
    "address": "National Museum of Slovenia (Muzejska ulica 1), NMS Metelkova (Maistrova ulica 1) and Center Rog (Trubarjeva cesta 72), 1000 Ljubljana",
    "lat": 46.04781,
    "lng": 14.503080999999996,
    "price": "Preveri vir",
    "description": "6th International Ceramics Triennial",
    "image": "https://www.visitljubljana.com/assets/EventRegistration/Images/UNICUM-2026-Jaka-Tersek-arhiv-Narodni-muzej-Slovenije-1__FocusFillMaxWyIwLjAwIiwiMC4wMCIsMTAwMCw0NTBd.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/unicum-2026",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "corn-labyrinth-2026-07-11",
    "title": "Corn Labyrinth Ljubljana",
    "category": "Glasba",
    "date": "2026-07-11",
    "endDate": "2026-10-31",
    "startTime": "09:00",
    "endTime": "20:00",
    "place": "Koruzni labirint Ljubljana, 1751 Stanežiče",
    "address": "Koruzni labirint Ljubljana, 1751 Stanežiče",
    "lat": 46.05057,
    "lng": 14.50205700000003,
    "price": "Preveri vir",
    "description": "Corn Jungle",
    "image": "https://www.visitljubljana.com/assets/Aktivnosti/Kultura-in-umetnost/Prireditve-na-prostem/Koruzni-labirint/Koruzni-labirint-Ljubljana-2026__FocusFillMaxWyIwLjAwIiwiMC4wMCIsMTAwMCw0NTBd.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/corn-labyrinth",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "open-kitchen-2026-09-25",
    "title": "Open Kitchen",
    "category": "Hrana",
    "date": "2026-09-25",
    "endDate": null,
    "startTime": "10:00",
    "endTime": "21:00",
    "place": "Pogačarjev trg, 1000 Ljubljana",
    "address": "Pogačarjev trg, 1000 Ljubljana",
    "lat": 46.0514,
    "lng": 14.5107,
    "price": "Preveri vir",
    "description": "Odprta kuhna (Open kitchen) is a one of a kind food market and one of the most popular culinary projects in Slovenia that brings food lovers and culinary adventurers to Ljubljana's city centre (Pogačarjev trg) every sunny Friday from March until November.",
    "image": "https://www.visitljubljana.com/assets/gallery/OK-20210820-LJ-216__FocusFillMaxWyIwLjAwIiwiMC4wMCIsMTAwMCw0NTBd.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/open-kitchen",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "artish-fest-2026-09-26",
    "title": "ARTish",
    "category": "Sejem",
    "date": "2026-09-26",
    "endDate": null,
    "startTime": "10:00",
    "endTime": "17:00",
    "place": "Gallusovo nabrežje (Gallus Embankment), 1000 Ljubljana",
    "address": "Gallusovo nabrežje (Gallus Embankment), 1000 Ljubljana",
    "lat": 46.05168,
    "lng": 14.503368000000119,
    "price": "Prost vstop",
    "description": "Exhibition Sales Art Festival",
    "image": "https://www.visitljubljana.com/assets/Element-Gallery/IMG_4254__FocusFillMaxWyIwLjAwIiwiMC4wMCIsMTAwMCw0NTBd.JPG",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/artish-fest",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "antique-flea-market-2026-09-27",
    "title": "Sunday Flea Market",
    "category": "Sejem",
    "date": "2026-09-27",
    "endDate": null,
    "startTime": "08:00",
    "endTime": "15:00",
    "place": "Breg, Ljubljana",
    "address": "Breg, Ljubljana",
    "lat": 46.0479,
    "lng": 14.5045,
    "price": "Prost vstop",
    "description": "Antique and Vintage Fair in Ljubljana",
    "image": "https://www.visitljubljana.com/assets/gallery/Bolsji-trg-Sejem-starin-Breg-2010-Dunja-Wedam-1__FocusFillMaxWyIwLjAwIiwiMC4wMCIsMTAwMCw0NTBd.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/antique-flea-market",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "promenade-concerts-of-local-brass-bands-2026-09-27",
    "title": "Sunday Promenade Concerts by Ljubljana's Wind Orchestras",
    "category": "Na prostem",
    "date": "2026-09-27",
    "endDate": null,
    "startTime": "11:00",
    "endTime": "12:00",
    "place": "Novi trg / Breg, 1000 Ljubljana",
    "address": "Novi trg / Breg, 1000 Ljubljana",
    "lat": 46.0479,
    "lng": 14.5045,
    "price": "Prost vstop",
    "description": "Promenade concerts by wind orchestras have been a tradition since 2013, making this year their fourteenth edition.",
    "image": "https://www.visitljubljana.com/assets/promenadni-koncerti-Novi-trg_Arhiv-KD-Pihalni-orkester-Ljubljana_IMG_20231001_114056_1920px__FocusFillMaxWyIwLjAwIiwiMC4wMCIsMTAwMCw0NTBd.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/promenade-concerts-of-local-brass-bands",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "uec-road-european-championships-2026-10-02",
    "title": "UEC Road European Championships 2026",
    "category": "Glasba",
    "date": "2026-10-02",
    "endDate": "2026-10-07",
    "startTime": "10:00",
    "endTime": "",
    "place": "Ljubljana",
    "address": "Ljubljana",
    "lat": 46.050869999999996,
    "lng": 14.505387,
    "price": "Prost vstop",
    "description": "Together with eleven municipalities across Central Slovenia and Gorenjska, Ljubljana will host the 2026 UEC Road European Championships from 2 to 7 October 2026, the largest cycling event held in Slovenia since the country gained independence.",
    "image": "https://www.visitljubljana.com/assets/Kolesarjenje/Dogodki/UEC-cestno-kolesarstvo-EKP_1065X600-urejena-1920px__FocusFillMaxWyItMC4wMSIsIi0wLjE3IiwxMDAwLDQ1MF0.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/uec-road-european-championships",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "european-table-tennis-championships-2026-10-11",
    "title": "European Table Tennis Championships",
    "category": "Glasba",
    "date": "2026-10-11",
    "endDate": "2026-10-18",
    "startTime": "10:00",
    "endTime": "",
    "place": "Ljubljana",
    "address": "Ljubljana",
    "lat": 46.05302,
    "lng": 14.50310200000003,
    "price": "Preveri vir",
    "description": "Best of European table tennis comes to Ljubljana",
    "image": "https://www.visitljubljana.com/assets/Prireditve/EP-v-namiznem-tenisu/roszie-pixabay-table-tennis-7415974_1920__FocusFillMaxWyItMC4wOCIsIjAuMzIiLDEwMDAsNDUwXQ.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/european-table-tennis-championships",
    "sourceName": "Visit Ljubljana"
  }
];
window.SPOTI_EVENTS_META = {"source":"Visit Ljubljana","updatedAt":"2026-09-21T09:53:38.3385261+00:00","automated":true,"count":8};
