/* Generated automatically by tools/update-events.ps1. */
window.SPOTI_EVENTS = [
  {
    "id": "library-under-treetops-2026-06-01",
    "title": "Library Under the Treetops",
    "category": "Družina",
    "date": "2026-06-01",
    "endDate": "2026-09-13",
    "startTime": "10:00",
    "endTime": "",
    "place": "Ljubljana",
    "address": "Ljubljana",
    "lat": 46.04942,
    "lng": 14.506042000000031,
    "price": "Prost vstop",
    "description": "An original outdoor reading project, intended for the general public, brings equipment and books each year to green corners of towns and cities, inviting people throughout the summer to read, browse, and relax under the trees.",
    "image": "https://www.visitljubljana.com/assets/gallery/Knjiznica-pod-krosnjami-Park-zvezda-2015-Matej-Perko__FocusFillMaxWyItMC4wMSIsIjAuNDMiLDEwMDAsNDUwXQ.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/library-under-treetops",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "ljubljana-festival-2026-06-21",
    "title": "Ljubljana Festival",
    "category": "Glasba",
    "date": "2026-06-21",
    "endDate": "2026-09-08",
    "startTime": "10:00",
    "endTime": "",
    "place": "Ljubljana",
    "address": "Ljubljana",
    "lat": 46.05332,
    "lng": 14.501931999999993,
    "price": "Preveri vir",
    "description": "The Ljubljana Festival, with its long history and tradition of presenting premier artistic events, contributes significantly to the cultural life of Ljubljana in the summer.",
    "image": "https://www.visitljubljana.com/assets/POI/Krizanke/Krizanke-photo-Joze-Macek-Domen-Pal-Branko-Ceak__FocusFillMaxWyIwLjAxIiwiMC4xNiIsMTAwMCw0NTBd.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/ljubljana-festival",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "unicum-2026-2026-07-08",
    "title": "UNICUM 2026",
    "category": "Glasba",
    "date": "2026-07-08",
    "endDate": "2026-10-15",
    "startTime": "10:00",
    "endTime": "18:00",
    "place": "National Museum of Slovenia (Muzejska ulica 1), NMS Metelkova (Maistrova ulica 1) and Center Rog (Trubarjeva cesta 72), 1000 Ljubljana",
    "address": "National Museum of Slovenia (Muzejska ulica 1), NMS Metelkova (Maistrova ulica 1) and Center Rog (Trubarjeva cesta 72), 1000 Ljubljana",
    "lat": 46.049119999999995,
    "lng": 14.50331200000003,
    "price": "Preveri vir",
    "description": "6th International Ceramics Triennial",
    "image": "https://www.visitljubljana.com/assets/EventRegistration/Images/UNICUM-2026-Jaka-Tersek-arhiv-Narodni-muzej-Slovenije-1__FocusFillMaxWyIwLjAwIiwiMC4wMCIsMTAwMCw0NTBd.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/unicum-2026",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "corn-labyrinth-2026-07-11",
    "title": "Corn Labyrinth Ljubljana",
    "category": "Glasba",
    "date": "2026-07-11",
    "endDate": "2026-10-31",
    "startTime": "09:00",
    "endTime": "20:00",
    "place": "Koruzni labirint Ljubljana, 1751 Stanežiče",
    "address": "Koruzni labirint Ljubljana, 1751 Stanežiče",
    "lat": 46.04987,
    "lng": 14.50718700000003,
    "price": "Preveri vir",
    "description": "Corn Jungle",
    "image": "https://www.visitljubljana.com/assets/Aktivnosti/Kultura-in-umetnost/Prireditve-na-prostem/Koruzni-labirint/Koruzni-labirint-Ljubljana-2026__FocusFillMaxWyIwLjAwIiwiMC4wMCIsMTAwMCw0NTBd.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/corn-labyrinth",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "hommage-a-france-rotar-25-years-later-2026-09-01",
    "title": "Hommage à France Rotar – 25 years later",
    "category": "Glasba",
    "date": "2026-09-01",
    "endDate": "2026-09-23",
    "startTime": "18:00",
    "endTime": "16:00",
    "place": "Križevniška Church",
    "address": "Križevniška Church",
    "lat": 46.0467,
    "lng": 14.5033,
    "price": "Preveri vir",
    "description": "Aktualni dogodek v programu Ljubljana Festivala.",
    "image": "https://www.visitljubljana.com/assets/EventRegistration/Images/France-Rotar__FocusFillWyIwLjAwIiwiMC4wMCIsNTAwLDMzMF0.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/hommage-a-france-rotar-25-years-later",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "open-kitchen-2026-09-04",
    "title": "Open Kitchen",
    "category": "Hrana",
    "date": "2026-09-04",
    "endDate": null,
    "startTime": "10:00",
    "endTime": "21:00",
    "place": "Pogačarjev trg, 1000 Ljubljana",
    "address": "Pogačarjev trg, 1000 Ljubljana",
    "lat": 46.0514,
    "lng": 14.5107,
    "price": "Preveri vir",
    "description": "Odprta kuhna (Open kitchen) is a one of a kind food market and one of the most popular culinary projects in Slovenia that brings food lovers and culinary adventurers to Ljubljana's city centre (Pogačarjev trg) every sunny Friday from March until November.",
    "image": "https://www.visitljubljana.com/assets/gallery/OK-20210820-LJ-216__FocusFillMaxWyIwLjAwIiwiMC4wMCIsMTAwMCw0NTBd.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/open-kitchen",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "mamma-mia-2026-09-04",
    "title": "Mamma Mia!",
    "category": "Glasba",
    "date": "2026-09-04",
    "endDate": null,
    "startTime": "20:00",
    "endTime": "21:30",
    "place": "Križanke Summer Theatre, Trg francoske revolucije 1, 1000 Ljubljana",
    "address": "Križanke Summer Theatre, Trg francoske revolucije 1, 1000 Ljubljana",
    "lat": 46.0467,
    "lng": 14.5033,
    "price": "Preveri vir",
    "description": "Aktualni dogodek v programu Ljubljana Festivala.",
    "image": "https://www.visitljubljana.com/assets/EventRegistration/Images/muzikal-mamma-mia-231__FocusFillWyIwLjAwIiwiMC4wMCIsNTAwLDMzMF0.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/mamma-mia",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "artish-fest-2026-09-05",
    "title": "ARTish",
    "category": "Sejem",
    "date": "2026-09-05",
    "endDate": null,
    "startTime": "10:00",
    "endTime": "17:00",
    "place": "Gallusovo nabrežje (Gallus Embankment), 1000 Ljubljana",
    "address": "Gallusovo nabrežje (Gallus Embankment), 1000 Ljubljana",
    "lat": 46.04779,
    "lng": 14.501879000000061,
    "price": "Prost vstop",
    "description": "Exhibition Sales Art Festival",
    "image": "https://www.visitljubljana.com/assets/Element-Gallery/IMG_4254__FocusFillMaxWyIwLjAwIiwiMC4wMCIsMTAwMCw0NTBd.JPG",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/artish-fest",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "ljubljana-sports-festival-2026-09-05",
    "title": "Ljubljana Sports Festival",
    "category": "Glasba",
    "date": "2026-09-05",
    "endDate": null,
    "startTime": "10:00",
    "endTime": "",
    "place": "Ljubljana",
    "address": "Ljubljana",
    "lat": 46.05251,
    "lng": 14.502550999999942,
    "price": "Prost vstop",
    "description": "Join a sports celebration in Tivoli Park in the centre of the city, where you can try out various sports activities and challenges free of charge from morning till evening.",
    "image": "https://www.visitljubljana.com/assets/gallery/Ljubljanski-festival-sporta-2023-foto-Arhiv-MOL__FocusFillMaxWyItMC4wNSIsIjAuMzIiLDEwMDAsNDUwXQ.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/ljubljana-sports-festival",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "antique-flea-market-2026-09-06",
    "title": "Sunday Flea Market",
    "category": "Sejem",
    "date": "2026-09-06",
    "endDate": null,
    "startTime": "08:00",
    "endTime": "15:00",
    "place": "Breg, Ljubljana",
    "address": "Breg, Ljubljana",
    "lat": 46.0479,
    "lng": 14.5045,
    "price": "Prost vstop",
    "description": "Antique and Vintage Fair in Ljubljana",
    "image": "https://www.visitljubljana.com/assets/gallery/Bolsji-trg-Sejem-starin-Breg-2010-Dunja-Wedam-1__FocusFillMaxWyIwLjAwIiwiMC4wMCIsMTAwMCw0NTBd.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/antique-flea-market",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "promenade-concerts-of-local-brass-bands-2026-09-06",
    "title": "Sunday Promenade Concerts by Ljubljana's Wind Orchestras",
    "category": "Na prostem",
    "date": "2026-09-06",
    "endDate": null,
    "startTime": "11:00",
    "endTime": "12:00",
    "place": "Novi trg / Breg, 1000 Ljubljana",
    "address": "Novi trg / Breg, 1000 Ljubljana",
    "lat": 46.0479,
    "lng": 14.5045,
    "price": "Prost vstop",
    "description": "Promenade concerts by wind orchestras have been a tradition since 2013, making this year their fourteenth edition.",
    "image": "https://www.visitljubljana.com/assets/promenadni-koncerti-Novi-trg_Arhiv-KD-Pihalni-orkester-Ljubljana_IMG_20231001_114056_1920px__FocusFillMaxWyIwLjAwIiwiMC4wMCIsMTAwMCw0NTBd.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/promenade-concerts-of-local-brass-bands",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "berliner-symphoniker-gudni-emilsson-conductor-khatia-buniatishvili-piano-2026-09-06",
    "title": "Berliner Symphoniker, Gudni Emilsson, conductor, Khatia Buniatishvili, piano",
    "category": "Glasba",
    "date": "2026-09-06",
    "endDate": null,
    "startTime": "20:00",
    "endTime": "00:00",
    "place": "Gallus Hall, Cankarjev dom",
    "address": "Gallus Hall, Cankarjev dom",
    "lat": 46.0515,
    "lng": 14.4994,
    "price": "Preveri vir",
    "description": "Aktualni dogodek v programu Ljubljana Festivala.",
    "image": "https://www.visitljubljana.com/assets/EventRegistration/Images/khatia-buniatishvili-1__FocusFillWyIwLjAyIiwiLTAuNjciLDUwMCwzMzBd.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/berliner-symphoniker-gudni-emilsson-conductor-khatia-buniatishvili-piano",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "staatskapelle-dresden-daniele-gatti-conductor-2026-09-07",
    "title": "Staatskapelle Dresden, Daniele Gatti, conductor",
    "category": "Glasba",
    "date": "2026-09-07",
    "endDate": null,
    "startTime": "20:00",
    "endTime": "00:00",
    "place": "Gallus Hall, Cankarjev dom",
    "address": "Gallus Hall, Cankarjev dom",
    "lat": 46.0515,
    "lng": 14.4994,
    "price": "Preveri vir",
    "description": "Aktualni dogodek v programu Ljubljana Festivala.",
    "image": "https://www.visitljubljana.com/assets/EventRegistration/Images/STAATSKAPELLE-DRESDEN__FocusFillWyIwLjAxIiwiMC4wOCIsNTAwLDMzMF0.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/staatskapelle-dresden-daniele-gatti-conductor",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "baltic-sea-philharmonic-robert-trevino-conductor-lana-trotovsek-violin-2026-09-08",
    "title": "Baltic Sea Philharmonic, Robert Trevino, conductor, Lana Trotovšek, violin",
    "category": "Glasba",
    "date": "2026-09-08",
    "endDate": null,
    "startTime": "20:00",
    "endTime": "00:00",
    "place": "Gallus Hall, Cankarjev dom",
    "address": "Gallus Hall, Cankarjev dom",
    "lat": 46.0515,
    "lng": 14.4994,
    "price": "Preveri vir",
    "description": "Aktualni dogodek v programu Ljubljana Festivala.",
    "image": "https://www.visitljubljana.com/assets/EventRegistration/Images/BALTIC-SEA-PHILHARMONIC__FocusFillWyIwLjAwIiwiMC4wMCIsNTAwLDMzMF0.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/baltic-sea-philharmonic-robert-trevino-conductor-lana-trotovsek-violin",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "uec-road-european-championships-2026-10-02",
    "title": "UEC Road European Championships 2026",
    "category": "Glasba",
    "date": "2026-10-02",
    "endDate": "2026-10-07",
    "startTime": "10:00",
    "endTime": "",
    "place": "Ljubljana",
    "address": "Ljubljana",
    "lat": 46.052229999999994,
    "lng": 14.506522999999971,
    "price": "Prost vstop",
    "description": "Together with eleven municipalities across Central Slovenia and Gorenjska, Ljubljana will host the 2026 UEC Road European Championships from 2 to 7 October 2026, the largest cycling event held in Slovenia since the country gained independence.",
    "image": "https://www.visitljubljana.com/assets/Kolesarjenje/Dogodki/UEC-cestno-kolesarstvo-EKP_1065X600-urejena-1920px__FocusFillMaxWyItMC4wMSIsIi0wLjE3IiwxMDAwLDQ1MF0.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/uec-road-european-championships",
    "sourceName": "Visit Ljubljana"
  }
];
window.SPOTI_EVENTS_META = {"source":"Visit Ljubljana","updatedAt":"2026-09-04T08:49:31.4163567+00:00","automated":true,"count":15};
