/* Generated automatically by tools/update-events.ps1. */
window.SPOTI_EVENTS = [
  {
    "id": "unicum-2026-2026-07-08",
    "title": "UNICUM 2026",
    "category": "Glasba",
    "date": "2026-07-08",
    "endDate": "2026-10-15",
    "startTime": "10:00",
    "endTime": "18:00",
    "place": "National Museum of Slovenia (Muzejska ulica 1), NMS Metelkova (Maistrova ulica 1) and Center Rog (Trubarjeva cesta 72), 1000 Ljubljana",
    "address": "National Museum of Slovenia (Muzejska ulica 1), NMS Metelkova (Maistrova ulica 1) and Center Rog (Trubarjeva cesta 72), 1000 Ljubljana",
    "lat": 46.050959999999996,
    "lng": 14.505596000000015,
    "price": "Preveri vir",
    "description": "6th International Ceramics Triennial",
    "image": "https://www.visitljubljana.com/assets/EventRegistration/Images/UNICUM-2026-Jaka-Tersek-arhiv-Narodni-muzej-Slovenije-1__FocusFillMaxWyIwLjAwIiwiMC4wMCIsMTAwMCw0NTBd.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/unicum-2026",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "corn-labyrinth-2026-07-11",
    "title": "Corn Labyrinth Ljubljana",
    "category": "Glasba",
    "date": "2026-07-11",
    "endDate": "2026-10-31",
    "startTime": "09:00",
    "endTime": "20:00",
    "place": "Koruzni labirint Ljubljana, 1751 Stanežiče",
    "address": "Koruzni labirint Ljubljana, 1751 Stanežiče",
    "lat": 46.050059999999995,
    "lng": 14.50060599999994,
    "price": "Preveri vir",
    "description": "Corn Jungle",
    "image": "https://www.visitljubljana.com/assets/Aktivnosti/Kultura-in-umetnost/Prireditve-na-prostem/Koruzni-labirint/Koruzni-labirint-Ljubljana-2026__FocusFillMaxWyIwLjAwIiwiMC4wMCIsMTAwMCw0NTBd.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/corn-labyrinth",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "open-kitchen-2026-10-09",
    "title": "Open Kitchen",
    "category": "Hrana",
    "date": "2026-10-09",
    "endDate": null,
    "startTime": "10:00",
    "endTime": "21:00",
    "place": "Pogačarjev trg, 1000 Ljubljana",
    "address": "Pogačarjev trg, 1000 Ljubljana",
    "lat": 46.0514,
    "lng": 14.5107,
    "price": "Preveri vir",
    "description": "Odprta kuhna (Open kitchen) is a one of a kind food market and one of the most popular culinary projects in Slovenia that brings food lovers and culinary adventurers to Ljubljana's city centre (Pogačarjev trg) every sunny Friday from March until November.",
    "image": "https://www.visitljubljana.com/assets/gallery/OK-20210820-LJ-216__FocusFillMaxWyIwLjAwIiwiMC4wMCIsMTAwMCw0NTBd.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/open-kitchen",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "artish-fest-2026-10-10",
    "title": "ARTish",
    "category": "Sejem",
    "date": "2026-10-10",
    "endDate": null,
    "startTime": "10:00",
    "endTime": "17:00",
    "place": "Gallusovo nabrežje (Gallus Embankment), 1000 Ljubljana",
    "address": "Gallusovo nabrežje (Gallus Embankment), 1000 Ljubljana",
    "lat": 46.05383,
    "lng": 14.50158300000012,
    "price": "Prost vstop",
    "description": "Exhibition Sales Art Festival",
    "image": "https://www.visitljubljana.com/assets/Element-Gallery/IMG_4254__FocusFillMaxWyIwLjAwIiwiMC4wMCIsMTAwMCw0NTBd.JPG",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/artish-fest",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "antique-flea-market-2026-10-11",
    "title": "Sunday Flea Market",
    "category": "Sejem",
    "date": "2026-10-11",
    "endDate": null,
    "startTime": "08:00",
    "endTime": "15:00",
    "place": "Breg, Ljubljana",
    "address": "Breg, Ljubljana",
    "lat": 46.0479,
    "lng": 14.5045,
    "price": "Prost vstop",
    "description": "Antique and Vintage Fair in Ljubljana",
    "image": "https://www.visitljubljana.com/assets/gallery/Bolsji-trg-Sejem-starin-Breg-2010-Dunja-Wedam-1__FocusFillMaxWyIwLjAwIiwiMC4wMCIsMTAwMCw0NTBd.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/antique-flea-market",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "european-table-tennis-championships-2026-10-11",
    "title": "European Table Tennis Championships",
    "category": "Glasba",
    "date": "2026-10-11",
    "endDate": "2026-10-18",
    "startTime": "10:00",
    "endTime": "",
    "place": "Ljubljana",
    "address": "Ljubljana",
    "lat": 46.05009,
    "lng": 14.50710900000006,
    "price": "Preveri vir",
    "description": "Best of European table tennis comes to Ljubljana",
    "image": "https://www.visitljubljana.com/assets/Prireditve/EP-v-namiznem-tenisu/darko-jorgic_Namiznoteniska-zveza-Slovenije__FocusFillMaxWyIwLjA2IiwiLTAuMDgiLDEwMDAsNDUwXQ.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/european-table-tennis-championships",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "the-30th-nlb-ljubljana-marathon-2026-10-17",
    "title": "The 30th NLB Ljubljana Marathon",
    "category": "Glasba",
    "date": "2026-10-17",
    "endDate": "2026-10-18",
    "startTime": "10:00",
    "endTime": "",
    "place": "Ljubljana",
    "address": "Ljubljana",
    "lat": 46.05329,
    "lng": 14.50132900000006,
    "price": "Preveri vir",
    "description": "Every autumn, Ljubljana comes alive with the spirit of running. Thousands of runners, supporters, and visitors from around the world fill the streets of the Slovenian capital, creating one of the largest sporting events in Slovenia and the wider region.",
    "image": "https://www.visitljubljana.com/assets/B2B/Tradicionalne-prireditve/15-maraton__FocusFillMaxWyIwLjAwIiwiMC4wMCIsMTAwMCw0NTBd.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/the-30th-nlb-ljubljana-marathon",
    "sourceName": "Visit Ljubljana"
  },
  {
    "id": "november-gourmet-ljubljana-2026-11-01",
    "title": "November Gourmet Ljubljana",
    "category": "Glasba",
    "date": "2026-11-01",
    "endDate": "2026-11-30",
    "startTime": "10:00",
    "endTime": "",
    "place": "Ljubljana",
    "address": "Ljubljana",
    "lat": 46.04888,
    "lng": 14.49988799999997,
    "price": "Preveri vir",
    "description": "A Festival with Taste",
    "image": "https://www.visitljubljana.com/assets/1-Pisma-iz-Ljubljane/Avgust-2026/November-Gourmet-Ljubljana-2026__FocusFillMaxWyIwLjAwIiwiMC4wMCIsMTAwMCw0NTBd.jpg",
    "source": "https://www.visitljubljana.com/en/visitors/events/events-in-ljubljana/november-gourmet-ljubljana",
    "sourceName": "Visit Ljubljana"
  }
];
window.SPOTI_EVENTS_META = {"source":"Visit Ljubljana","updatedAt":"2026-10-08T11:19:56.0995226+00:00","automated":true,"count":8};
